### ISSUE TITLE
buy & hold example on colab fail

### ISSUE THREAD

**Issue by kruzel** [epymetheus/epymetheus#98]
https://colab.research.google.com/github/epymetheus/epymetheus/blob/main/examples/buy_and_hold.ipynb#scrollTo=zB-N6RXwl5vZ

![image](https://user-images.githubusercontent.com/975963/156888901-6f88f6d9-3f49-4952-9841-7554ab8453ea.png)

**Comment by simaki** [comment]
Thank you for reporting this. The examples are for older version of the library and no longer work
